# Generated by Django 4.0.3 on 2022-03-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subsribers',
            table='subsriberscd jeni',
        ),
    ]
