# Generated by Django 4.0.3 on 2022-03-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0002_alter_subsribers_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subsribers',
            table='subscribers',
        ),
    ]
